### ISSUE TITLE
Spelling correction in the title

### ISSUE THREAD

**Issue by robinpaulson** [Gnonthgol/JOSM-continuos-download#14]
The title should be JOSM-continuous-download, not JOSM-continuos-download.

**Comment by Gnonthgol** [comment]
Unfixable

**Comment by robinpaulson** [comment]
Github made changes a while back so repo names can be seamlessly changed without breaking anything https://github.com/blog/1508-repository-redirects-are-here and http://stackoverflow.com/questions/5751585/how-do-i-rename-a-repository-on-github

**Comment by Gnonthgol** [comment]
That does not help with the JOSM plugin system. I have proposed to make a transition plugin which would have the old name and install the new plugin with the corect name. If you want to do it I can assist.
