### ISSUE TITLE
JOSM #8836 - IllegalStateException: Timer already cancelled in continuos download plugin

### ISSUE THREAD

**Issue by don-vip** [Gnonthgol/JOSM-continuos-download#6]
See http://josm.openstreetmap.de/ticket/8836

**Comment by don-vip** [comment]
Situation has evolved a bit on our side: we do now provide support for plugins that are transferred to the JOSM Github organization, as explained here: https://github.com/JOSM/tofix-plugin/issues/21#issuecomment-148179719

Would you like to transfer your two plugins to the organization ? They are nice features and would deserve that we take care of them.

You would still of course remain the team leader, but that would allow us to maintain the translations and changes from public JOSM API, and most wanted tickets.

**Comment by don-vip** [comment]
Hello,
We still receive duplicate bug reports.
My offer to transfer this repository to the JOSM organization still stands: it would allow us to fix the few issues.

**Comment by Gnonthgol** [comment]
Did I refuse that? In case that is my bad.

14. jun. 2017 21.54 skrev "Vincent Privat" <notifications@github.com>:

**Comment by don-vip** [comment]
Fixed in https://github.com/JOSM/continuos-download/releases/tag/v1.2.5
